[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.2", default-features = false, features = ["minilp"] }
utils = { version = "0.1.0", path = "../utils" }
